services:
  mysql:
    image: mysql:9.4.0
    container_name: bookmymovie-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 30s

volumes:
  mysql_data:
