-- Insert dummy movies data
INSERT INTO MOVIE (MOVIE_ID, MOVIE_NAME, MOVIE_POSTER_URL, MOVIE_TAGS) VALUES
(1, 'The Matrix', 'https://via.placeholder.com/300x400?text=The+Matrix', 'Action,Sci-Fi'),
(2, 'Inception', 'https://via.placeholder.com/300x400?text=Inception', 'Action,Sci-Fi,Thriller'),
(3, 'The Dark Knight', 'https://via.placeholder.com/300x400?text=The+Dark+Knight', 'Action,Crime,Drama'),
(4, 'Pulp Fiction', 'https://via.placeholder.com/300x400?text=Pulp+Fiction', 'Crime,Drama'),
(5, 'The Shawshank Redemption', 'https://via.placeholder.com/300x400?text=The+Shawshank+Redemption', 'Drama'),
(6, 'Forrest Gump', 'https://via.placeholder.com/300x400?text=Forrest+Gump', 'Drama,Romance'),
(7, 'The Godfather', 'https://via.placeholder.com/300x400?text=The+Godfather', 'Crime,Drama'),
(8, 'Titanic', 'https://via.placeholder.com/300x400?text=Titanic', 'Drama,Romance'),
(9, 'Avatar', 'https://via.placeholder.com/300x400?text=Avatar', 'Action,Adventure,Fantasy'),
(10, 'Star Wars: A New Hope', 'https://via.placeholder.com/300x400?text=Star+Wars', 'Action,Adventure,Fantasy'),
(11, 'Jurassic Park', 'https://via.placeholder.com/300x400?text=Jurassic+Park', 'Action,Adventure,Sci-Fi'),
(12, 'Back to the Future', 'https://via.placeholder.com/300x400?text=Back+to+the+Future', 'Adventure,Comedy,Sci-Fi'),
(13, 'The Lion King', 'https://via.placeholder.com/300x400?text=The+Lion+King', 'Animation,Adventure,Drama'),
(14, 'Spider-Man', 'https://via.placeholder.com/300x400?text=Spider-Man', 'Action,Adventure'),
(15, 'Iron Man', 'https://via.placeholder.com/300x400?text=Iron+Man', 'Action,Adventure,Sci-Fi'),
(16, 'The Avengers', 'https://via.placeholder.com/300x400?text=The+Avengers', 'Action,Adventure,Sci-Fi'),
(17, 'Guardians of the Galaxy', 'https://via.placeholder.com/300x400?text=Guardians+of+the+Galaxy', 'Action,Adventure,Comedy'),
(18, 'Black Panther', 'https://via.placeholder.com/300x400?text=Black+Panther', 'Action,Adventure,Sci-Fi'),
(19, 'Wonder Woman', 'https://via.placeholder.com/300x400?text=Wonder+Woman', 'Action,Adventure,Fantasy'),
(20, 'Captain Marvel', 'https://via.placeholder.com/300x400?text=Captain+Marvel', 'Action,Adventure,Sci-Fi');

                                                                           (1, 'Toy Story (1995)', 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', 'Adventure|Animation|Children|Comedy|Fantasy'),
                                                                           (2, 'Jumanji (1995)', 'https://image.tmdb.org/t/p/w500/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg', 'Adventure|Children|Fantasy'),
                                                                           (3, 'Grumpier Old Men (1995)', 'https://image.tmdb.org/t/p/w500/1FSXpIsln6kZrskfE71qE4VTaL.jpg', 'Comedy|Romance'),
                                                                           (4, 'Waiting to Exhale (1995)', 'https://image.tmdb.org/t/p/w500/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg', 'Comedy|Drama|Romance'),
                                                                           (5, 'The Shawshank Redemption (1994)', 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'Drama'),
                                                                           (6, 'The Godfather (1972)', 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'Crime|Drama'),
                                                                           (7, 'The Dark Knight (2008)', 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'Action|Crime|Drama'),
                                                                           (8, 'The Godfather Part II (1974)', 'https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'Crime|Drama'),
                                                                           (9, '12 Angry Men (1957)', 'https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg', 'Drama'),
                                                                           (10, 'Schindlers List (1993)', 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'Biography|Drama|History'),
                                                                           (11, 'The Lord of the Rings: The Return of the King (2003)', 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'Adventure|Drama|Fantasy'),
                                                                           (12, 'Pulp Fiction (1994)', 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', 'Crime|Drama'),
                                                                           (13, 'The Lord of the Rings: The Fellowship of the Ring (2001)', 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', 'Adventure|Drama|Fantasy'),
                                                                           (14, 'Forrest Gump (1994)', 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', 'Drama|Romance'),
                                                                           (15, 'The Good the Bad and the Ugly (1966)', 'https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'Western'),
                                                                           (16, 'Fight Club (1999)', 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 'Drama'),
                                                                           (17, 'Inception (2010)', 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', 'Action|Adventure|Sci-Fi|Thriller'),
                                                                           (18, 'The Lord of the Rings: The Two Towers (2002)', 'https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg', 'Adventure|Drama|Fantasy'),
                                                                           (19, 'Star Wars: Episode V - The Empire Strikes Back (1980)', 'https://image.tmdb.org/t/p/w500/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg', 'Action|Adventure|Fantasy|Sci-Fi'),
                                                                           (20, 'The Matrix (1999)', 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 'Action|Sci-Fi'),
                                                                           (21, 'Goodfellas (1990)', 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', 'Biography|Crime|Drama'),
                                                                           (22, 'One Flew Over the Cuckoos Nest (1975)', 'https://image.tmdb.org/t/p/w500/3jskjz5U5zs7a2W3cRwh2EcI83l.jpg', 'Drama'),
                                                                           (23, 'Se7en (1995)', 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg', 'Crime|Drama|Mystery|Thriller'),
                                                                           (24, 'Seven Samurai (1954)', 'https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg', 'Action|Drama'),
                                                                           (25, 'Its a Wonderful Life (1946)', 'https://image.tmdb.org/t/p/w500/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg', 'Drama|Family|Fantasy'),
                                                                           (26, 'The Silence of the Lambs (1991)', 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg', 'Crime|Drama|Thriller'),
                                                                           (27, 'Saving Private Ryan (1998)', 'https://image.tmdb.org/t/p/w500/uqx37ACv9XDhr5IGWfREXmqnndo.jpg', 'Drama|War'),
                                                                           (28, 'City of God (2002)', 'https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg', 'Crime|Drama'),
                                                                           (29, 'Interstellar (2014)', 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'Adventure|Drama|Sci-Fi'),
                                                                           (30, 'Life Is Beautiful (1997)', 'https://image.tmdb.org/t/p/w500/74hLDKjD5aGYOotO6esUVaeISa2.jpg', 'Comedy|Drama|Romance|War'),
                                                                           (31, 'The Green Mile (1999)', 'https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg', 'Crime|Drama|Fantasy'),
                                                                           (32, 'Star Wars (1977)', 'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', 'Action|Adventure|Fantasy|Sci-Fi'),
                                                                           (33, 'Terminator 2: Judgment Day (1991)', 'https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi2RhfjjurTqb.jpg', 'Action|Sci-Fi'),
                                                                           (34, 'Back to the Future (1985)', 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg', 'Adventure|Comedy|Sci-Fi'),
                                                                           (35, 'Spirited Away (2001)', 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'Animation|Adventure|Family|Fantasy'),
                                                                           (36, 'The Pianist (2002)', 'https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg', 'Biography|Drama|Music|War'),
                                                                           (37, 'Psycho (1960)', 'https://image.tmdb.org/t/p/w500/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg', 'Horror|Mystery|Thriller'),
                                                                           (38, 'Gladiator (2000)', 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', 'Action|Adventure|Drama'),
                                                                           (39, 'The Lion King (1994)', 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', 'Animation|Adventure|Drama|Family'),
                                                                           (40, 'The Departed (2006)', 'https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg', 'Crime|Drama|Thriller'),
                                                                           (41, 'Whiplash (2014)', 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg', 'Drama|Music'),
                                                                           (42, 'The Prestige (2006)', 'https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg', 'Drama|Mystery|Sci-Fi|Thriller'),
                                                                           (43, 'The Usual Suspects (1995)', 'https://img.vwassets.com/orpheum.com.au/vertical_38caa210-793a-4616-8d16-eae47201efc2.jpg', 'Crime|Drama|Mystery|Thriller'),
                                                                           (44, 'Casablanca (1942)', 'https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSLezBOY0Qxh8a.jpg', 'Drama|Romance|War'),
                                                                           (45, 'Grave of the Fireflies (1988)', 'https://image.tmdb.org/t/p/w500/k9tv1rXZbOhH7eiCk4XYRlHLz4k.jpg', 'Animation|Drama|War'),
                                                                           (46, 'Cinema Paradiso (1988)', 'https://image.tmdb.org/t/p/w500/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg', 'Drama|Romance'),
                                                                           (47, 'Rear Window (1954)', 'https://image.tmdb.org/t/p/w500/ILVF0eJxHMddjxeQhswFtpMtqx.jpg', 'Mystery|Thriller'),
                                                                           (48, 'Alien (1979)', 'https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg', 'Horror|Sci-Fi'),
                                                                           (49, 'City Lights (1931)', 'https://image.tmdb.org/t/p/w500/bXNvzjULc9jrOVhGfjcc64uKZmZ.jpg', 'Comedy|Drama|Romance'),
                                                                           (50, 'Apocalypse Now (1979)', 'https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg', 'Drama|Mystery|War'),
                                                                           (51, 'Memento (2000)', 'https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg', 'Mystery|Thriller'),
                                                                           (52, 'Indiana Jones and the Raiders of the Lost Ark (1981)', 'https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg', 'Action|Adventure'),
                                                                           (53, 'Django Unchained (2012)', 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg', 'Drama|Western'),
                                                                           (54, 'The Avengers (2012)', 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg', 'Action|Adventure|Sci-Fi');