-- Insert initial data for theatres and screens

-- Insert theatres
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'CGV Grand Indonesia', 'Jakarta Pusat');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'XXI Pondok Indah', 'Jakarta Selatan');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'Cinepolis Depok Town Square', 'Depok');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'XXI Bogor Trade Mall', 'Bogor');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'CGV Summarecon Bekasi', 'Bekasi');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'CGV Paris Van Java', 'Bandung');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'XXI Cihampelas Walk', 'Bandung');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'Cinepolis BTC', 'Bandung');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'XXI Trans Studio Mall Bandung', 'Bandung');
INSERT INTO THEATRE (THEATRE_ID, THEATRE_NAME, THEATRE_CITY)
VALUES (DEFAULT, 'CGV 23 Paskal', 'Bandung');



-- Insert screens
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 1, 50);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 1, 64);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 1, 25);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 1, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 1, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 2, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 2, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 2, 25);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 3, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 3, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 3, 25);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 4, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 5, 100);
INSERT INTO SCREEN (SCREEN_ID, THEATRE_ID, SEATS_NUM)
VALUES (DEFAULT, 5, 100);